### ISSUE TITLE
The Blockchain contains blocks with unknown version

### ISSUE THREAD

**Issue by tabz11** [ladimolnar/BitcoinDatabaseGenerator#10]
Hi ,

I am trying to use this software to get the blocks, but getting following error
ERROR: The blockchain contains blocks with an unknown version. Unknown block version: 3652501241 (D9B4BEF9).

I have tried several times but same error is coming all the time

**Comment by ladimolnar** [comment]
Hello tabz11. I am swamped at the moment. I'll try to get to this in a week or so.

**Comment by tabz11** [comment]
Thanks

**Comment by tabz11** [comment]
Hi,

Managed to resolve above issue, just re-synchronised my blocks. Now error is coming at block # 820 as unknown block.

Thanks,

**Comment by ladimolnar** [comment]
This is fixed in the latest release V 1.9
https://github.com/ladimolnar/BitcoinDatabaseGenerator/releases/tag/v1.9
