### ISSUE TITLE
Unknown block version: 805306375 (300000007)

### ISSUE THREAD

**Issue by mrp1** [ladimolnar/BitcoinDatabaseGenerator#12]
Using BitcoinDatabaseGenerator V1.8 

File: blk00820.dat. Transfering data: 88%
ERROR: The blockchain contains blocks with an unknown version. Unknown block version: 805306375 (300000007).

The exception is thrown in BlockchainParser.cs at line 167. 

Tried 1st with blockchain that had been on my system for 3 years and active daily. THEN the Blockchain was completely reloaded from scratch (24 hrs..) and the same error...

**Comment by ladimolnar** [comment]
Hello mrp1. I am swamped at the moment. I'll try to get to this in a week or so.

**Comment by mrp1** [comment]
Thanks... I'll keep a eye out...

**Comment by tabz11** [comment]
I am getting same error but after 44%.

**Comment by ladimolnar** [comment]
This is fixed in the latest release V 1.9
https://github.com/ladimolnar/BitcoinDatabaseGenerator/releases/tag/v1.9

**Comment by mrp1** [comment]
THANK YOU...  I'll give it a try this coming week....
