### ISSUE TITLE
Can not connect to Mysql database

### ISSUE THREAD

**Issue by crazybytes** [ladimolnar/BitcoinDatabaseGenerator#14]
System.Data.SqlClient.SqlException (0x80131904)

The Mysql database is running perfectly. Other programs can acces the sql database.
I used the following command:

BitcoinDatabaseGenerator /BlockchainPath C:\Bitcoin\data\blocks\ /SqlServerName localhost /SqlDbName bitcoin /SqlUserName root /SqlPassword root /DropDb

Plz help.

**Comment by ladimolnar** [comment]
This app can only save to Ms SQL Server. It does not work with mysql.
