### ISSUE TITLE
Which database does the code work with

### ISSUE THREAD

**Issue by GSongHashrate** [ladimolnar/BitcoinDatabaseGenerator#3]
Hi,

Does the code only works with MS SQL Server?
I've tried MySQL which gives error for database connection.

**Comment by ladimolnar** [comment]
Yes, it only works with MS SQL Server

**Comment by crazybytes** [comment]
I have the same issue with mysql server. Other programs can connect to the sql server perfectly, but BitcoinDatabaseGenerator.exe gives error when trying to connect.

It only works with MS SQL Server? I try that one.

**Comment by ladimolnar** [comment]
Yes crazybytes, like I said earlier, only works with Ms. SQL Server
