### ISSUE TITLE
Unknown version issue

### ISSUE THREAD

**Issue by allanng78** [ladimolnar/BitcoinDatabaseGenerator#6]
Hi,
I have encountered this error when I try to extract .dat to ms sql. The error is below.

   File: blk00443.dat. Transferring data:  39%
ERROR: The blockchain contains blocks with an unknown version. Unknown block version: 805306368.

Please help me.
Thank.

allan

**Comment by ladimolnar** [comment]
The latest release (V1.5) should fix this issue. Please sync to the latest version or download the latest release and try again.
