### ISSUE TITLE
Unknown Version Error

### ISSUE THREAD

**Issue by Velveeta22** [ladimolnar/BitcoinDatabaseGenerator#7]
File: blk00490.dat. Transferring data: 57%
ERROR: The blockchain contains blocks with an unknown version.  Unknown block version: 536870912.

**Comment by chang-joon-won** [comment]
Thank you for your software.
but, recently, I had same error. see the followings.

Database "bitcoin" found.
Deleting from database the data about blockchain file: blk00490.dat
    File: blk00490.dat. Transferring data:  70%
ERROR: The blockchain contains blocks with an unknown version. Unknown block version: 536870912.

**Comment by ladimolnar** [comment]
I will try to find some time this coming weekend and update the code.

**Comment by ladimolnar** [comment]
Fixed in Release V 1.6

**Comment by Velveeta22** [comment]
Great work, thank you.  Block 490 has now imported.
